on:
  pull_request:
  push:
    branches: [master, main]
jobs:
  docker-test:
    name: Docker install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t eis_toolkit -f ./Dockerfile-docs .
      # - name: Run mkdocs in Docker container
      #   run: |
      #     docker run -v ./site/pdf/:/eis_toolkit/site/pdf/ --env ENABLE_PDF_EXPORT=1 eis_toolkit poetry run mkdocs build
      - uses: actions/upload-artifact@v4
        with:
          name: document.pdf
          path: ./site/pdf/document.pdf
      - name: Run pytest in Docker container
        run: docker run eis_toolkit poetry run pytest -v
